services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12202:8080"
    volumes:
      - .:/app
    command: air -c .air.toml
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example_password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example_password
      - ME_CONFIG_MONGODB_URL=mongodb://root:example_password@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo

volumes:
  mongo_data:
